spring:
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  profiles: default
  jpa:
    database: HSQL

---

spring:
  profiles: cloud
  jpa:
    database: MYSQL

---

spring:
  profiles: openshift
  jpa:
    database: MYSQL
